[package]
name = "Morphing"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui-notify = "0.17.0"
egui_extras = "0.29.1"
rfd = "0.15.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "morph_benchmark"
harness = false